#Testing Environment for the Rocket Richard Award, actual code used for the application is found in finalized_scripts/rocketrichard.py

In [5]:
import numpy as np
import pandas as pd
from nhlpy import NHLClient
import ast

In [15]:
#clear csv of empty entries and format into a pandas csv
def clear_csv(csv_path):
    print(csv_path)
    df = pd.read_csv(csv_path, encoding='ascii')
    df = df.dropna()
    return df
rocket_richard = clear_csv("../data/formattedwebscraped/rocketrichard.csv")
rocket_richard

../data/formattedwebscraped/rocketrichard.csv

,szn,winner,runner_up,finalist
1,2025-26,('https://www.nhl.com/player/nathan-mackinnon-...,('https://www.nhl.com/player/cole-caufield-848...,('https://www.nhl.com/player/connor-mcdavid-84...
3,2024-25,('https://www.nhl.com/player/leon-draisaitl-84...,('https://www.nhl.com/player/william-nylander-...,[('https://www.nhl.com/player/alex-ovechkin-84...
5,2023-24,('https://www.nhl.com/player/auston-matthews-8...,('https://www.nhl.com/player/sam-reinhart-8477...,('https://www.nhl.com/player/zach-hyman-847578...
7,2022-23,('https://www.nhl.com/player/connor-mcdavid-84...,('https://www.nhl.com/player/david-pastrnak-84...,('https://www.nhl.com/player/mikko-rantanen-84...
9,2021-22,('https://www.nhl.com/player/auston-matthews-8...,('https://www.nhl.com/player/leon-draisaitl-84...,('https://www.nhl.com/player/chris-kreider-847...
11,2020-21,('https://www.nhl.com/player/auston-matthews-8...,('https://www.nhl.com/player/connor-mcdavid-84...,('https://www.nhl.com/player/alex-debrincat-84...
13,2019-20,[('https://www.nhl.com/player/david-pastrnak-8...,('https://www.nhl.com/player/auston-matthews-8...,('https://www.nhl.com/player/leon-draisaitl-84...
15,2018-19,('https://www.nhl.com/player/alex-ovechkin-847...,('https://www.nhl.com/player/leon-draisaitl-84...,('https://www.nhl.com/player/john-tavares-8475...
17,2017-18,('https://www.nhl.com/player/alex-ovechkin-847...,('https://www.nhl.com/player/patrik-laine-8479...,('https://www.nhl.com/player/william-karlsson-...
19,2016-17,('https://www.nhl.com/player/sidney-crosby-847...,('https://www.nhl.com/player/nikita-kucherov-8...,('https://www.nhl.com/player/auston-matthews-8...
21,2015-16,('https://www.nhl.com/player/alex-ovechkin-847...,('https://www.nhl.com/player/patrick-kane-8474...,('https://www.nhl.com/player/jamie-benn-847399...
23,2014-15,('https://www.nhl.com/player/alex-ovechkin-847...,('https://www.nhl.com/player/steven-stamkos-84...,('https://www.nhl.com/player/rick-nash-8470041...
25,2013-14,('https://www.nhl.com/player/alex-ovechkin-847...,('https://www.nhl.com/player/corey-perry-84706...,('https://www.nhl.com/player/joe-pavelski-8470...
27,2012-13,('https://www.nhl.com/player/alex-ovechkin-847...,('https://www.nhl.com/player/steven-stamkos-84...,('https://www.nhl.com/player/john-tavares-8475...
29,2011-12,('https://www.nhl.com/player/steven-stamkos-84...,('https://www.nhl.com/player/evgeni-malkin-847...,('https://www.nhl.com/player/marian-gaborik-84...
31,2010-11,('https://www.nhl.com/player/corey-perry-84706...,('https://www.nhl.com/player/steven-stamkos-84...,('https://www.nhl.com/player/jarome-iginla-846...
35,2008-09,('https://www.nhl.com/player/alex-ovechkin-847...,('https://www.nhl.com/player/jeff-carter-84706...,('https://www.nhl.com/player/zach-parise-84706...
37,2007-08,('https://www.nhl.com/player/alex-ovechkin-847...,('https://www.nhl.com/player/ilya-kovalchuk-84...,('https://www.nhl.com/player/jarome-iginla-846...
39,2006-07,('https://www.nhl.com/player/vincent-lecavalie...,('https://www.nhl.com/player/dany-heatley-8468...,('https://www.nhl.com/player/teemu-selanne-845...
41,2005-06,('https://www.nhl.com/player/jonathan-cheechoo...,('https://www.nhl.com/player/jaromir-jagr-8448...,[('https://www.nhl.com/player/ilya-kovalchuk-8...
45,2002-03,('https://www.nhl.com/player/milan-hejduk-8460...,('https://www.nhl.com/player/markus-naslund-84...,('https://www.nhl.com/player/todd-bertuzzi-845...
49,2000-01,('https://www.nhl.com/player/pavel-bure-845573...,('https://www.nhl.com/player/joe-sakic-8451101...,('https://www.nhl.com/player/jaromir-jagr-8448...
51,1999-00,('https://www.nhl.com/player/pavel-bure-845573...,('https://www.nhl.com/player/owen-nolan-844989...,('https://www.nhl.com/player/tony-amonte-84554...

In [88]:
client = NHLClient()
def extractPlayerID(url):

    '''
    purpose:    parses a url and returns that player's id (used by the NHL API) 
    parameters: player url (string)
    returns:    unique player ID (string)
    '''
    #every player ID used by the NHL website and API is 7 digits long
    split = url.rsplit("-")
    return split[-1]

def placeToStats(place_list):
    '''
    purpose:    takes a list of players from the webscraped csv and returns a list of the stats of players in the list
    parameters: place_list (a pandas dataframe of tuples)
    returns:    list of player IDs
    '''
    ids = []
    seasons = place_list.iloc[:,0]
    players = place_list.iloc[:,1]
    seasons = seasons.tolist()
    players = players.tolist()

    for i in range(len(players)):
        playerTuple = ast.literal_eval(players[i])    
        if type(playerTuple) != tuple:      #working with an entry where multiple players won this award
            for entry in playerTuple:
                id = extractPlayerID(entry[0])
                ids.append((seasons[i],id))
            continue
        
        id = extractPlayerID(playerTuple[0])
        ids.append((seasons[i],id))
    return ids

In [ ]:
#extract the player stats of all players in the first, second and third places of the award
first_place = rocket_richard[['szn','winner']]
second_place = rocket_richard[['szn','runner_up']]
third_place = rocket_richard[['szn','finalist']]

first_ids = placeToStats(first_place)
second_ids = placeToStats(second_place)
third_ids = placeToStats(third_place)

[('2025-26', '8477492'),
 ('2024-25', '8477934'),
 ('2023-24', '8479318'),
 ('2022-23', '8478402'),
 ('2021-22', '8479318'),
 ('2020-21', '8479318'),
 ('2019-20', '8477956'),
 ('2019-20', '8471214'),
 ('2018-19', '8471214'),
 ('2017-18', '8471214'),
 ('2016-17', '8471675'),
 ('2015-16', '8471214'),
 ('2014-15', '8471214'),
 ('2013-14', '8471214'),
 ('2012-13', '8471214'),
 ('2011-12', '8474564'),
 ('2010-11', '8470621'),
 ('2008-09', '8471214'),
 ('2007-08', '8471214'),
 ('2006-07', '8467329'),
 ('2005-06', '8467357'),
 ('2002-03', '8460577'),
 ('2000-01', '8455738'),
 ('1999-00', '8455738')]

In [86]:
#Rocket Richard is a statistic directed award, so no models are actually required, just fetch goals of skaters in a given season
#this block of code cuts down the ~700 players in the league to a handful of top scorers

from nhlpy.api.query.builder import QueryBuilder, QueryContext
from nhlpy.api.query.filters.season import SeasonQuery
from nhlpy.api.query.filters.game_type import GameTypeQuery
from nhlpy.api.query.filters.position import PositionQuery, PositionTypes

filters=[
    GameTypeQuery(game_type="2"),                       #2 = regular season, 1=pre-season, 3=playoffs, 4=allstargame
    SeasonQuery("20242025","20242025"),                 #should be put out for an input of the current season
    PositionQuery(position=PositionTypes.ALL_FORWARDS)  
]
query_builder = QueryBuilder()
query_context: QueryContext = query_builder.build(filters=filters)

query_context.fact_query = "gamesPlayed>=1"

data = client.stats.skater_stats_with_query_context(
    report_type='summary',
    query_context=query_context,
    aggregate=True
)

print(len(data['data']))
data['data']

25

[{'assists': 84,
  'evGoals': 29,
  'evPoints': 75,
  'faceoffWinPct': 0.5,
  'gameWinningGoals': 9,
  'gamesPlayed': 78,
  'goals': 37,
  'lastName': 'Kucherov',
  'otGoals': 1,
  'penaltyMinutes': 45,
  'playerId': 8476453,
  'plusMinus': 22,
  'points': 121,
  'pointsPerGame': 1.55128,
  'positionCode': 'R',
  'ppGoals': 8,
  'ppPoints': 46,
  'shGoals': 0,
  'shPoints': 0,
  'shootingPct': 0.13962,
  'shootsCatches': 'L',
  'shots': 265,
  'skaterFullName': 'Nikita Kucherov',
  'timeOnIcePerGame': 1271.3717},
 {'assists': 84,
  'evGoals': 23,
  'evPoints': 78,
  'faceoffWinPct': 0.49933,
  'gameWinningGoals': 5,
  'gamesPlayed': 79,
  'goals': 32,
  'lastName': 'MacKinnon',
  'otGoals': 1,
  'penaltyMinutes': 41,
  'playerId': 8477492,
  'plusMinus': 25,
  'points': 116,
  'pointsPerGame': 1.46835,
  'positionCode': 'C',
  'ppGoals': 9,
  'ppPoints': 38,
  'shGoals': 0,
  'shPoints': 0,
  'shootingPct': 0.1,
  'shootsCatches': 'R',
  'shots': 320,
  'skaterFullName': 'Nathan MacKinnon',
  'timeOnIcePerGame': 1366.9493},
 {'assists': 54,
  'evGoals': 36,
  'evPoints': 73,
  'faceoffWinPct': 0.54347,
  'gameWinningGoals': 11,
  'gamesPlayed': 71,
  'goals': 52,
  'lastName': 'Draisaitl',
  'otGoals': 6,
  'penaltyMinutes': 34,
  'playerId': 8477934,
  'plusMinus': 32,
  'points': 106,
  'pointsPerGame': 1.49295,
  'positionCode': 'C',
  'ppGoals': 16,
  'ppPoints': 33,
  'shGoals': 0,
  'shPoints': 0,
  'shootingPct': 0.21666,
  'shootsCatches': 'L',
  'shots': 240,
  'skaterFullName': 'Leon Draisaitl',
  'timeOnIcePerGame': 1291.0422},
 {'assists': 63,
  'evGoals': 34,
  'evPoints': 83,
  'faceoffWinPct': 0.375,
  'gameWinningGoals': 4,
  'gamesPlayed': 82,
  'goals': 43,
  'lastName': 'Pastrnak',
  'otGoals': 3,
  'penaltyMinutes': 42,
  'playerId': 8477956,
  'plusMinus': 0,
  'points': 106,
  'pointsPerGame': 1.29268,
  'positionCode': 'R',
  'ppGoals': 9,
  'ppPoints': 23,
  'shGoals': 0,
  'shPoints': 0,
  'shootingPct': 0.13479,
  'shootsCatches': 'R',
  'shots': 319,
  'skaterFullName': 'David Pastrnak',
  'timeOnIcePerGame': 1211.1707},
 {'assists': 75,
  'evGoals': 20,
  'evPoints': 67,
  'faceoffWinPct': 0.29411,
  'gameWinningGoals': 7,
  'gamesPlayed': 81,
  'goals': 27,
  'lastName': 'Marner',
  'otGoals': 3,
  'penaltyMinutes': 14,
  'playerId': 8478483,
  'plusMinus': 18,
  'points': 102,
  'pointsPerGame': 1.25925,
  'positionCode': 'R',
  'ppGoals': 6,
  'ppPoints': 33,
  'shGoals': 1,
  'shPoints': 2,
  'shootingPct': 0.15606,
  'shootsCatches': 'R',
  'shots': 173,
  'skaterFullName': 'Mitch Marner',
  'timeOnIcePerGame': 1278.9259},
 {'assists': 74,
  'evGoals': 17,
  'evPoints': 69,
  'faceoffWinPct': 0.4768,
  'gameWinningGoals': 3,
  'gamesPlayed': 67,
  'goals': 26,
  'lastName': 'McDavid',
  'otGoals': 0,
  'penaltyMinutes': 37,
  'playerId': 8478402,
  'plusMinus': 20,
  'points': 100,
  'pointsPerGame': 1.49253,
  'positionCode': 'C',
  'ppGoals': 9,
  'ppPoints': 31,
  'shGoals': 0,
  'shPoints': 0,
  'shootingPct': 0.13265,
  'shootsCatches': 'L',
  'shots': 196,
  'skaterFullName': 'Connor McDavid',
  'timeOnIcePerGame': 1321.8805},
 {'assists': 56,
  'evGoals': 30,
  'evPoints': 67,
  'faceoffWinPct': 0.125,
  'gameWinningGoals': 8,
  'gamesPlayed': 82,
  'goals': 41,
  'lastName': 'Connor',
  'otGoals': 2,
  'penaltyMinutes': 25,
  'playerId': 8478398,
  'plusMinus': 17,
  'points': 97,
  'pointsPerGame': 1.18292,
  'positionCode': 'L',
  'ppGoals': 9,
  'ppPoints': 28,
  'shGoals': 2,
  'shPoints': 2,
  'shootingPct': 0.15355,
  'shootsCatches': 'L',
  'shots': 267,
  'skaterFullName': 'Kyle Connor',
  'timeOnIcePerGame': 1223.6829},
 {'assists': 66,
  'evGoals': 22,
  'evPoints': 58,
  'faceoffWinPct': 0.45614,
  'gameWinningGoals': 3,
  'gamesPlayed': 77,
  'goals': 28,
  'lastName': 'Eichel',
  'otGoals': 0,
  'penaltyMinutes': 8,
  'playerId': 8478403,
  'plusMinus': 32,
  'points': 94,
  'pointsPerGame': 1.22077,
  'positionCode': 'C',
  'ppGoals': 5,
  'ppPoints': 34,
  'shGoals': 1,
  'shPoints': 2,
  'shootingPct': 0.12017,
  'shootsCatches': 'R',
  'shots': 233,
  'skaterFullName': 'Jack Eichel',
  'timeOnIcePerGame': 1232.0129},
 {'assists': 58,
  'evGoals': 21,
  'evPoints': 64,
  'faceoffWinPct': 0.57014,
  'gameWinningGoals': 10,
  'gamesPlayed': 80,
  'goals': 33,
  'lastName': 'Crosby',
  'otGoals': 4,
  'penaltyMinutes': 31,
  'playerId': 8471675,
  'plusMinus': -20,
  'points': 91,
  'pointsPerGame': 1.1375,
  'positionCode': 'C',
  'ppGoals': 12,
  'ppPoints': 27,
  'shGoals': 0,
  'shPoints': 0,
  'shootingPct': 0.14537,
  'shootsCatches': 'L',
  'shots': 227,
  'skaterFullName': 'Sidney Crosby',
  'timeOnIcePerGame': 1222.475},
 {'assists': 60,
  'evGoals': 20,
  'evPoints': 53,
  'faceoffWinPct': 0.33333,
  'gameWinningGoals': 5,
  'gamesPlayed': 81,
  'goals': 30,
  'lastName': 'Keller',
  'otGoals': 1,
  'penaltyMinutes': 28,
  'playerId': 8479343,
  'plusMinus': -12,
  'points': 90,
  'pointsPerGame': 1.11111,
  'positionCode': 'R',
  'ppGoals': 10,
  'ppPoints': 37,
  'shGoals': 0,
  'shPoints': 0,
  'shootingPct': 0.13761,
  'shootsCatches': 'L',
  'shots': 218,
  'skaterFullName': 'Clayton Keller',
  'timeOnIcePerGame': 1147.0864},
 {'assists': 55,
  'evGoals': 32,
  'evPoints': 72,
  'faceoffWinPct': 0.34782,
  'gameWinningGoals': 4,
  'gamesPlayed': 82,
  'goals': 35,
  'lastName': 'Hagel',
  'otGoals': 0,
  'penaltyMinutes': 58,
  'playerId': 8479542,
  'plusMinus': 33,
  'points': 90,
  'pointsPerGame': 1.09756,
  'positionCode': 'L',
  'ppGoals': 0,
  'ppPoints': 11,
  'shGoals': 3,
  'shPoints': 7,
  'shootingPct': 0.1535,
  'shootsCatches': 'L',
  'shots': 228,
  'skaterFullName': 'Brandon Hagel',
  'timeOnIcePerGame': 1244.5975},
 {'assists': 52,
  'evGoals': 29,
  'evPoints': 63,
  'faceoffWinPct': 0.0,
  'gameWinningGoals': 3,
  'gamesPlayed': 80,
  'goals': 37,
  'lastName': 'Panarin',
  'otGoals': 0,
  'penaltyMinutes': 16,
  'playerId': 8478550,
  'plusMinus': -9,
  'points': 89,
  'pointsPerGame': 1.1125,
  'positionCode': 'L',
  'ppGoals': 8,
  'ppPoints': 26,
  'shGoals': 0,
  'shPoints': 0,
  'shootingPct': 0.15611,
  'shootsCatches': 'R',
  'shots': 237,
  'skaterFullName': 'Artemi Panarin',
  'timeOnIcePerGame': 1180.9875},
 {'assists': 59,
  'evGoals': 24,
  'evPoints': 60,
  'faceoffWinPct': 0.51593,
  'gameWinningGoals': 9,
  'gamesPlayed': 82,
  'goals': 30,
  'lastName': 'Suzuki',
  'otGoals': 5,
  'penaltyMinutes': 8,
  'playerId': 8480018,
  'plusMinus': 19,
  'points': 89,
  'pointsPerGame': 1.08536,
  'positionCode': 'C',
  'ppGoals': 4,
  'ppPoints': 27,
  'shGoals': 2,
  'shPoints': 2,
  'shootingPct': 0.17441,
  'shootsCatches': 'R',
  'shots': 172,
  'skaterFullName': 'Nick Suzuki',
  'timeOnIcePerGame': 1203.6341},
 {'assists': 67,
  'evGoals': 15,
  'evPoints': 50,
  'faceoffWinPct': 0.0,
  'gameWinningGoals': 2,
  'gamesPlayed': 81,
  'goals': 21,
  'lastName': 'Bratt',
  'otGoals': 0,
  'penaltyMinutes': 18,
  'playerId': 8479407,
  'plusMinus': 5,
  'points': 88,
  'pointsPerGame': 1.08641,
  'positionCode': 'L',
  'ppGoals': 4,
  'ppPoints': 34,
  'shGoals': 2,
  'shPoints': 4,
  'shootingPct': 0.11666,
  'shootsCatches': 'L',
  'shots': 180,
  'skaterFullName': 'Jesper Bratt',
  'timeOnIcePerGame': 1136.8888},
 {'assists': 56,
  'evGoals': 21,
  'evPoints': 62,
  'faceoffWinPct': 0.52941,
  'gameWinningGoals': 6,
  'gamesPlayed': 82,
  'goals': 32,
  'lastName': 'Rantanen',
  'otGoals': 0,
  'penaltyMinutes': 60,
  'playerId': 8478420,
  'plusMinus': 13,
  'points': 88,
  'pointsPerGame': 1.07317,
  'positionCode': 'R',
  'ppGoals': 11,
  'ppPoints': 26,
  'shGoals': 0,
  'shPoints': 0,
  'shootingPct': 0.15094,
  'shootsCatches': 'L',
  'shots': 212,
  'skaterFullName': 'Mikko Rantanen',
  'timeOnIcePerGame': 1274.9512},
 {'assists': 48,
  'evGoals': 28,
  'evPoints': 62,
  'faceoffWinPct': 0.49447,
  'gameWinningGoals': 11,
  'gamesPlayed': 82,
  'goals': 39,
  'lastName': 'Scheifele',
  'otGoals': 3,
  'penaltyMinutes': 61,
  'playerId': 8476460,
  'plusMinus': 12,
  'points': 87,
  'pointsPerGame': 1.06097,
  'positionCode': 'C',
  'ppGoals': 11,
  'ppPoints': 25,
  'shGoals': 0,
  'shPoints': 0,
  'shootingPct': 0.21546,
  'shootsCatches': 'R',
  'shots': 181,
  'skaterFullName': 'Mark Scheifele',
  'timeOnIcePerGame': 1226.3902},
 {'assists': 39,
  'evGoals': 33,
  'evPoints': 54,
  'faceoffWinPct': 0.49673,
  'gameWinningGoals': 8,
  'gamesPlayed': 82,
  'goals': 45,
  'lastName': 'Nylander',
  'otGoals': 2,
  'penaltyMinutes': 26,
  'playerId': 8477939,
  'plusMinus': 10,
  'points': 84,
  'pointsPerGame': 1.02439,
  'positionCode': 'R',
  'ppGoals': 12,
  'ppPoints': 30,
  'shGoals': 0,
  'shPoints': 0,
  'shootingPct': 0.17786,
  'shootsCatches': 'R',
  'shots': 253,
  'skaterFullName': 'William Nylander',
  'timeOnIcePerGame': 1170.5731},
 {'assists': 56,
  'evGoals': 15,
  'evPoints': 46,
  'faceoffWinPct': 0.37777,
  'gameWinningGoals': 8,
  'gamesPlayed': 79,
  'goals': 27,
  'lastName': 'Necas',
  'otGoals': 0,
  'penaltyMinutes': 16,
  'playerId': 8480039,
  'plusMinus': 5,
  'points': 83,
  'pointsPerGame': 1.05063,
  'positionCode': 'C',
  'ppGoals': 12,
  'ppPoints': 37,
  'shGoals': 0,
  'shPoints': 0,
  'shootingPct': 0.13917,
  'shootsCatches': 'R',
  'shots': 194,
  'skaterFullName': 'Martin Necas',
  'timeOnIcePerGame': 1139.9113},
 {'assists': 40,
  'evGoals': 26,
  'evPoints': 51,
  'faceoffWinPct': 0.48532,
  'gameWinningGoals': 7,
  'gamesPlayed': 77,
  'goals': 42,
  'lastName': 'Point',
  'otGoals': 2,
  'penaltyMinutes': 7,
  'playerId': 8478010,
  'plusMinus': 17,
  'points': 82,
  'pointsPerGame': 1.06493,
  'positionCode': 'C',
  'ppGoals': 16,
  'ppPoints': 31,
  'shGoals': 0,
  'shPoints': 0,
  'shootingPct': 0.22222,
  'shootsCatches': 'R',
  'shots': 189,
  'skaterFullName': 'Brayden Point',
  'timeOnIcePerGame': 1168.7532},
 {'assists': 52,
  'evGoals': 22,
  'evPoints': 55,
  'faceoffWinPct': 0.5238,
  'gameWinningGoals': 6,
  'gamesPlayed': 82,
  'goals': 30,
  'lastName': 'Duchene',
  'otGoals': 1,
  'penaltyMinutes': 12,
  'playerId': 8475168,
  'plusMinus': 13,
  'points': 82,
  'pointsPerGame': 1.0,
  'positionCode': 'C',
  'ppGoals': 8,
  'ppPoints': 27,
  'shGoals': 0,
  'shPoints': 0,
  'shootingPct': 0.19736,
  'shootsCatches': 'L',
  'shots': 152,
  'skaterFullName': 'Matt Duchene',
  'timeOnIcePerGame': 1028.5731},
 {'assists': 53,
  'evGoals': 20,
  'evPoints': 48,
  'faceoffWinPct': 0.5369,
  'gameWinningGoals': 3,
  'gamesPlayed': 82,
  'goals': 29,
  'lastName': 'Strome',
  'otGoals': 0,
  'penaltyMinutes': 34,
  'playerId': 8478440,
  'plusMinus': 2,
  'points': 82,
  'pointsPerGame': 1.0,
  'positionCode': 'C',
  'ppGoals': 9,
  'ppPoints': 34,
  'shGoals': 0,
  'shPoints': 0,
  'shootingPct': 0.19463,
  'shootsCatches': 'L',
  'shots': 149,
  'skaterFullName': 'Dylan Strome',
  'timeOnIcePerGame': 1043.0243},
 {'assists': 60,
  'evGoals': 17,
  'evPoints': 61,
  'faceoffWinPct': 0.54783,
  'gameWinningGoals': 5,
  'gamesPlayed': 70,
  'goals': 21,
  'lastName': 'Thomas',
  'otGoals': 1,
  'penaltyMinutes': 20,
  'playerId': 8480023,
  'plusMinus': 20,
  'points': 81,
  'pointsPerGame': 1.15714,
  'positionCode': 'C',
  'ppGoals': 3,
  'ppPoints': 19,
  'shGoals': 1,
  'shPoints': 1,
  'shootingPct': 0.14482,
  'shootsCatches': 'R',
  'shots': 145,
  'skaterFullName': 'Robert Thomas',
  'timeOnIcePerGame': 1197.4857},
 {'assists': 42,
  'evGoals': 21,
  'evPoints': 45,
  'faceoffWinPct': 0.41245,
  'gameWinningGoals': 4,
  'gamesPlayed': 79,
  'goals': 39,
  'lastName': 'Reinhart',
  'otGoals': 0,
  'penaltyMinutes': 27,
  'playerId': 8477933,
  'plusMinus': 6,
  'points': 81,
  'pointsPerGame': 1.02531,
  'positionCode': 'C',
  'ppGoals': 13,
  'ppPoints': 30,
  'shGoals': 5,
  'shPoints': 6,
  'shootingPct': 0.18309,
  'shootsCatches': 'R',
  'shots': 213,
  'skaterFullName': 'Sam Reinhart',
  'timeOnIcePerGame': 1230.1392},
 {'assists': 39,
  'evGoals': 23,
  'evPoints': 51,
  'faceoffWinPct': 0.46093,
  'gameWinningGoals': 5,
  'gamesPlayed': 80,
  'goals': 41,
  'lastName': 'Guentzel',
  'otGoals': 0,
  'penaltyMinutes': 24,
  'playerId': 8477404,
  'plusMinus': 18,
  'points': 80,
  'pointsPerGame': 1.0,
  'positionCode': 'C',
  'ppGoals': 17,
  'ppPoints': 28,
  'shGoals': 1,
  'shPoints': 1,
  'shootingPct': 0.18894,
  'shootsCatches': 'L',
  'shots': 217,
  'skaterFullName': 'Jake Guentzel',
  'timeOnIcePerGame': 1199.5625},
 {'assists': 45,
  'evGoals': 26,
  'evPoints': 61,
  'faceoffWinPct': 0.36842,
  'gameWinningGoals': 6,
  'gamesPlayed': 82,
  'goals': 35,
  'lastName': 'Robertson',
  'otGoals': 1,
  'penaltyMinutes': 18,
  'playerId': 8480027,
  'plusMinus': 10,
  'points': 80,
  'pointsPerGame': 0.9756,
  'positionCode': 'L',
  'ppGoals': 9,
  'ppPoints': 19,
  'shGoals': 0,
  'shPoints': 0,
  'shootingPct': 0.16587,
  'shootsCatches': 'L',
  'shots': 211,
  'skaterFullName': 'Jason Robertson',
  'timeOnIcePerGame': 1067.6097}]

In [87]:
above25goals = data['data']         #based on the filtering above, this is a hard coded 2024-2025 season handful of players that are most likely to win rocket richard
df = pd.DataFrame(above25goals)

#add an extra column of average time on ice across the whole season
df['averageTOI'] = np.zeros(df.shape[0])
df['averageTOI'] = (df['timeOnIcePerGame']/60)
df

,assists,evGoals,evPoints,faceoffWinPct,gameWinningGoals,gamesPlayed,goals,lastName,otGoals,penaltyMinutes,...,ppGoals,ppPoints,shGoals,shPoints,shootingPct,shootsCatches,shots,skaterFullName,timeOnIcePerGame,averageTOI
0,84,29,75,0.50000,9,78,37,Kucherov,1,45,...,8,46,0,0,0.13962,L,265,Nikita Kucherov,1271.3717,21.189528
1,84,23,78,0.49933,5,79,32,MacKinnon,1,41,...,9,38,0,0,0.10000,R,320,Nathan MacKinnon,1366.9493,22.782488
2,54,36,73,0.54347,11,71,52,Draisaitl,6,34,...,16,33,0,0,0.21666,L,240,Leon Draisaitl,1291.0422,21.517370
3,63,34,83,0.37500,4,82,43,Pastrnak,3,42,...,9,23,0,0,0.13479,R,319,David Pastrnak,1211.1707,20.186178
4,75,20,67,0.29411,7,81,27,Marner,3,14,...,6,33,1,2,0.15606,R,173,Mitch Marner,1278.9259,21.315432
5,74,17,69,0.47680,3,67,26,McDavid,0,37,...,9,31,0,0,0.13265,L,196,Connor McDavid,1321.8805,22.031342
6,56,30,67,0.12500,8,82,41,Connor,2,25,...,9,28,2,2,0.15355,L,267,Kyle Connor,1223.6829,20.394715
7,66,22,58,0.45614,3,77,28,Eichel,0,8,...,5,34,1,2,0.12017,R,233,Jack Eichel,1232.0129,20.533548
8,58,21,64,0.57014,10,80,33,Crosby,4,31,...,12,27,0,0,0.14537,L,227,Sidney Crosby,1222.4750,20.374583
9,60,20,53,0.33333,5,81,30,Keller,1,28,...,10,37,0,0,0.13761,L,218,Clayton Keller,1147.0864,19.118107
10,55,32,72,0.34782,4,82,35,Hagel,0,58,...,0,11,3,7,0.15350,L,228,Brandon Hagel,1244.5975,20.743292
11,52,29,63,0.00000,3,80,37,Panarin,0,16,...,8,26,0,0,0.15611,R,237,Artemi Panarin,1180.9875,19.683125
12,59,24,60,0.51593,9,82,30,Suzuki,5,8,...,4,27,2,2,0.17441,R,172,Nick Suzuki,1203.6341,20.060568
13,67,15,50,0.00000,2,81,21,Bratt,0,18,...,4,34,2,4,0.11666,L,180,Jesper Bratt,1136.8888,18.948147
14,56,21,62,0.52941,6,82,32,Rantanen,0,60,...,11,26,0,0,0.15094,L,212,Mikko Rantanen,1274.9512,21.249187
15,48,28,62,0.49447,11,82,39,Scheifele,3,61,...,11,25,0,0,0.21546,R,181,Mark Scheifele,1226.3902,20.439837
16,39,33,54,0.49673,8,82,45,Nylander,2,26,...,12,30,0,0,0.17786,R,253,William Nylander,1170.5731,19.509552
17,56,15,46,0.37777,8,79,27,Necas,0,16,...,12,37,0,0,0.13917,R,194,Martin Necas,1139.9113,18.998522
18,40,26,51,0.48532,7,77,42,Point,2,7,...,16,31,0,0,0.22222,R,189,Brayden Point,1168.7532,19.479220
19,52,22,55,0.52380,6,82,30,Duchene,1,12,...,8,27,0,0,0.19736,L,152,Matt Duchene,1028.5731,17.142885
20,53,20,48,0.53690,3,82,29,Strome,0,34,...,9,34,0,0,0.19463,L,149,Dylan Strome,1043.0243,17.383738
21,60,17,61,0.54783,5,70,21,Thomas,1,20,...,3,19,1,1,0.14482,R,145,Robert Thomas,1197.4857,19.958095
22,42,21,45,0.41245,4,79,39,Reinhart,0,27,...,13,30,5,6,0.18309,R,213,Sam Reinhart,1230.1392,20.502320
23,39,23,51,0.46093,5,80,41,Guentzel,0,24,...,17,28,1,1,0.18894,L,217,Jake Guentzel,1199.5625,19.992708
24,45,26,61,0.36842,6,82,35,Robertson,1,18,...,9,19,0,0,0.16587,L,211,Jason Robertson,1067.6097,17.793495

In [69]:
#recreate the above but for any year
from nhlpy.api.query.builder import QueryBuilder, QueryContext
from nhlpy.api.query.filters.season import SeasonQuery
from nhlpy.api.query.filters.game_type import GameTypeQuery
from nhlpy.api.query.filters.position import PositionQuery, PositionTypes

def predictHistoricalRRWinner(year):
    '''
    purpose:    takes a given season and produces the historical winner of the Rocket Richard award for that given year 
    parameters: year (string) either in yyyy or yyyyyyyy format
    returns:    a tuple (winner name, # of goals, player ID)
    '''
    #format year for the filter (is a string when inputted)
    if len(year) == 4:
        int_year = int(year)
        interval = (int_year,int_year+1)
        year_interval = str(interval[0]) + str(interval[1])
    elif len(year) == 8:    #20252026
        year_interval = year
    else:
        raise SyntaxError("requires yyyy or yyyyyyyy format of season year")
    
    
    filters=[
    GameTypeQuery(game_type="2"),                       #2 = regular season, 1=pre-season, 3=playoffs, 4=allstargame
    SeasonQuery(year_interval,year_interval),                             #should be put out for an input of the current season
    PositionQuery(position=PositionTypes.ALL_FORWARDS)  
    ]
    query_builder = QueryBuilder()
    query_context: QueryContext = query_builder.build(filters=filters)

    query_context.fact_query = "gamesPlayed>=1 and goals >=25"  #this is a hard coded assumption, the lower the goal threshold the more players to work with

    data = client.stats.skater_stats_with_query_context(
        report_type='summary',
        query_context=query_context,
        aggregate=True
    )

    dfa25 = pd.DataFrame(data['data'])      #a dataframe of all players above 25 goals in a given season
    
    #now, "predict" the historical winner of this year
    #since RR is only determined by the highest # of goals, sort as such

    highlight = dfa25[['goals','skaterFullName', 'playerId']]
    standings = highlight.sort_values(by='goals',ascending=False)
    winner = standings.iloc[0]
    return tuple(winner)

In [70]:
#tests

print(predictHistoricalRRWinner("2024"))       #enter starting year OR interval year
#print(predictHistoricalRRWinner("20252026"))   #

(np.int64(52), 'Leon Draisaitl', np.int64(8477934))

### Milestone #1: Identify Past Rocket Winners and start a particular dataset with these labels put together

In [66]:
#strip seasons
seasons = rocket_richard['szn']
for szn in seasons:
    nohyphen = szn.split("-")
    szn = nohyphen[0]
    print(szn, predictHistoricalRRWinner(szn))

2025 (np.int64(53), 'Nathan MacKinnon', np.int64(8477492))
2024 (np.int64(52), 'Leon Draisaitl', np.int64(8477934))
2023 (np.int64(69), 'Auston Matthews', np.int64(8479318))
2022 (np.int64(64), 'Connor McDavid', np.int64(8478402))
2021 (np.int64(60), 'Auston Matthews', np.int64(8479318))
2020 (np.int64(41), 'Auston Matthews', np.int64(8479318))
2019 (np.int64(48), 'Alex Ovechkin', np.int64(8471214))
2018 (np.int64(51), 'Alex Ovechkin', np.int64(8471214))
2017 (np.int64(49), 'Alex Ovechkin', np.int64(8471214))
2016 (np.int64(44), 'Sidney Crosby', np.int64(8471675))
2015 (np.int64(50), 'Alex Ovechkin', np.int64(8471214))
2014 (np.int64(53), 'Alex Ovechkin', np.int64(8471214))
2013 (np.int64(51), 'Alex Ovechkin', np.int64(8471214))
2012 (np.int64(32), 'Alex Ovechkin', np.int64(8471214))
2011 (np.int64(60), 'Steven Stamkos', np.int64(8474564))
2010 (np.int64(50), 'Corey Perry', np.int64(8470621))
2008 (np.int64(56), 'Alex Ovechkin', np.int64(8471214))
2007 (np.int64(65), 'Alex Ovechkin', np.int64(8471214))
2006 (np.int64(52), 'Vincent Lecavalier', np.int64(8467329))
2005 (np.int64(56), 'Jonathan Cheechoo', np.int64(8467357))
2002 (np.int64(50), 'Milan Hejduk', np.int64(8460577))
2000 (np.int64(59), 'Pavel Bure', np.int64(8455738))
1999 (np.int64(58), 'Pavel Bure', np.int64(8455738))