## EDGE Model Ver. B

### This notebook will contain a variant of the Rocket Richard Baseline Predictor made in rr1.ipynb, that is, this variant will be using General Skater Stats (GSS) + EDGE Stats -- AKA: EDGE Model Ver. B
#### This is done for the sake of model fine tuning and evaluating performance

In [194]:
import numpy as np
import pandas as pd
from nhlpy import NHLClient
import ast
from helpersrr import clear_csv, extractPlayerID, placeToStats, fetchSkaterStats, labelWinners, formatEdgeStats
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier


import importlib
import helpersrr
importlib.reload(helpersrr)

In [ ]:
#global variables
ranks = False
versionA = False    #version A has no shot details, version B has ALL shot details

client = NHLClient()
rocket_richard = clear_csv("../data/formattedwebscraped/rocketrichard.csv")

first_place = rocket_richard[['szn','winner']]
first_ids = placeToStats(first_place)
second_place = rocket_richard[['szn', 'runner_up']]
second_ids = placeToStats(second_place)
third_place = rocket_richard[['szn', 'finalist']]
third_ids = placeToStats(third_place)

../data/formattedwebscraped/rocketrichard.csv

### Milestone 1: Get EDGE Statistics from the API and place them in data/api/EDGEstats

In [196]:
#DO NOT RUN THIS IF COMMENTED -- essentially places relevant EDGE stats files into the data/api/EDGEstats folder
#edgeSzns = ['20212022','20222023','20232024','20242025','20252026']
#fetchSkaterStats('20212022',csv=True,edge=True)
#for season in edgeSzns:
#    fetchSkaterStats(season, csv=True, edge=True)
#    print(f"done season {season}")

### Milestone 2: Make the new feature set (GSS + EDGE Stats)

In [197]:
#get the playerIds of the top 3
rr2firstids = placeToStats(rocket_richard[['szn','winner']])
rr2secondids = placeToStats(rocket_richard[['szn','runner_up']])
rr2thirdids = placeToStats(rocket_richard[['szn','finalist']])

In [198]:
#split training sets and testing set
edgeSzns = ['20212022','20222023','20232024','20242025','20252026']
trainingSets = []
testingSet = []

to_drop = ['positionCode','lastName','teamAbbrevs','shGoals','shPoints']    #keep full name instead of last name
for year in edgeSzns:
    if ranks == True:
        #if versionA == True:
        modifiedDf = labelWinners(year=year[:4], first_ids=rr2firstids, second_ids=rr2secondids, third_ids=rr2thirdids, rank=True, edge=True, versionA=False)
        #else:
        #    modifiedDf = labelWinners(year=year[:4], first_ids=rr2firstids, second_ids=rr2secondids, third_ids=rr2thirdids, rank=True, edge=True, versionA=False)
    else:
        #if versionA == True:
        modifiedDf = labelWinners(year=year[:4], first_ids=rr2firstids, second_ids=rr2secondids, third_ids=rr2thirdids, rank=False, edge=True, versionA=False)
        #else:
        #    modifiedDf = labelWinners(year=year[:4], first_ids=rr2firstids, second_ids=rr2secondids, third_ids=rr2thirdids, rank=False, edge=True, versionA=False)
    
    feature_df = modifiedDf.drop(columns=to_drop)
    feature_df = feature_df.dropna()
    feature_df .loc[feature_df ['shootsCatches'] == "L", 'shootsCatches'] = 0    #encode L -> 0 to fit model
    feature_df .loc[feature_df ['shootsCatches'] == "R", 'shootsCatches'] = 1    #encode R -> 1 to fit model
    
    if year == "20252026":  #2025-2026 will be the testing year
        testingSet.append(feature_df)
    else:
        trainingSets.append(feature_df)
print(len(testingSet), len(trainingSets))

masterTraining = pd.DataFrame()
for train in trainingSets:
    masterTraining = pd.concat([masterTraining,train])

masterTesting = pd.DataFrame()
masterTesting = pd.concat([masterTesting,testingSet[0]])

1 4

### Milestone 3: Train model

In [199]:
if ranks == False:
    train_x = masterTraining.drop(columns=['skaterFullName','rrWinner','playerId','seasonId'])
    train_y = masterTraining['rrWinner']
else:
    train_x = masterTesting.drop(columns=['skaterFullName','rrRank','playerId','seasonId'])
    train_y = masterTesting['rrRank']

model1 = LogisticRegression(max_iter=20000, class_weight="balanced")
model1.fit(train_x,train_y)

#new addition: RandomForest
model2 = RandomForestClassifier(n_estimators=100)
model2.fit(train_x,train_y)

RandomForestClassifier()

### Milestone 4: Test on EDGE + GSS of 2025-2026

In [200]:
test2025 = masterTesting
if ranks == False:
    test_x = test2025.drop(columns=['skaterFullName','rrWinner','playerId','seasonId'])
    test_y = test2025['rrWinner']
else:
    test_x = test2025.drop(columns=['skaterFullName','rrRank','playerId','seasonId'])
    test_y = test2025['rrRank']


pred_y1 = model1.predict(test_x)
predictions = pd.Series(pred_y1)
predictions = predictions.rename('predictions')
predictions = predictions.to_frame()
results = test2025.join(predictions)


pred_y2 = model2.predict(test_x)
predictions2 = pd.Series(pred_y2)
predictions2 = predictions2.rename('predictions')
predictions2 = predictions2.to_frame()
results2 = test2025.join(predictions2)

In [201]:
#for model 1

if ranks == False:
    show = results.loc[results['predictions'] == 1]
else:
    show = results.loc[results['predictions'] != 0]
    show = show.dropna()
    hyman = results.loc[results['rrRank'] != 0]

#view influences on the model
feature_names = train_x.columns
coefficients = pd.Series(model1.coef_[0],index=feature_names)
print(coefficients.sort_values())

with pd.option_context("display.max_rows", None, "display.max_columns", None):      #view full prediction list
    display(show)

gamesPlayed                    -0.361129
Outside L Shots                -0.179139
longShots                      -0.167994
skatingSpeed                   -0.124613
assists                        -0.114347
topShotSpeed                   -0.101587
L Point Shots                  -0.096343
L Net Side Shots               -0.082360
R Point Shots                  -0.073175
R Circle Shots                 -0.054829
penaltyMinutes                 -0.047267
ppGoals                        -0.044173
shots                          -0.038729
Low Slot Shots                 -0.037730
R Corner Shots                 -0.035932
Offensive Neutral Zone Shots   -0.031214
totalDistanceSkated            -0.019854
shootsCatches                  -0.014036
longGoals                      -0.012857
L Corner Shots                 -0.007499
timeOnIcePerGame               -0.002509
defensiveZonePctg              -0.002002
faceoffWinPct                  -0.001141
neutralZonePctg                -0.000724
offensiveZonePctg              -0.000706
averageTOI                     -0.000042
shootingPct                     0.000838
Center Point Shots              0.001524
pointsPerGame                   0.006937
distanceMaxGame                 0.007712
highShots                       0.011852
ppPoints                        0.031574
Beyond Red Line Shots           0.039354
High Slot Shots                 0.041828
Behind the Net Shots            0.042112
plusMinus                       0.049156
Crease Shots                    0.049581
gameWinningGoals                0.065235
midShots                        0.074306
L Circle Shots                  0.087307
otGoals                         0.105153
evPoints                        0.131909
R Net Side Shots                0.134985
Outside R Shots                 0.162800
highGoals                       0.188769
points                          0.203660
midGoals                        0.231564
goals                           0.318007
evGoals                         0.338420
dtype: float64

,assists,evGoals,evPoints,faceoffWinPct,gameWinningGoals,gamesPlayed,goals,otGoals,penaltyMinutes,playerId,plusMinus,points,pointsPerGame,ppGoals,ppPoints,seasonId,shootingPct,shootsCatches,shots,skaterFullName,timeOnIcePerGame,topShotSpeed,skatingSpeed,totalDistanceSkated,distanceMaxGame,longShots,longGoals,midShots,midGoals,highShots,highGoals,offensiveZonePctg,neutralZonePctg,defensiveZonePctg,Behind the Net Shots,Beyond Red Line Shots,Center Point Shots,Crease Shots,High Slot Shots,L Circle Shots,L Corner Shots,L Net Side Shots,L Point Shots,Low Slot Shots,Offensive Neutral Zone Shots,Outside L Shots,Outside R Shots,R Circle Shots,R Corner Shots,R Net Side Shots,R Point Shots,averageTOI,rrWinner,predictions
2,74,42,97,0.51049,7,80,53,1,39,8477492,57,127,1.5875,11,30,20252026,0.15142,1,350,Nathan MacKinnon,1335.7125,146.4342,39.8786,456.0059,7.8713,32,6,149,20,83,19,0.466145,0.18097,0.352885,3,3,16,11,42,77,1,19,11,72,5,38,12,30,0,5,5,22.261875,1.0,1.0

findings/conclusions on the above can be found in commitlog.md

In [202]:
#for model 2 -- uses SHAP to visualize predictions (later)
if ranks == False:
    show = results2.loc[results2['predictions'] == 1]
else:
    show = results2.loc[results2['predictions'] != 0]
    show = show.dropna()
    hyman = results2.loc[results2['rrRank'] != 0]
show

Empty DataFrame
Columns: [assists, evGoals, evPoints, faceoffWinPct, gameWinningGoals, gamesPlayed, goals, otGoals, penaltyMinutes, playerId, plusMinus, points, pointsPerGame, ppGoals, ppPoints, seasonId, shootingPct, shootsCatches, shots, skaterFullName, timeOnIcePerGame, topShotSpeed, skatingSpeed, totalDistanceSkated, distanceMaxGame, longShots, longGoals, midShots, midGoals, highShots, highGoals, offensiveZonePctg, neutralZonePctg, defensiveZonePctg, Behind the Net Shots, Beyond Red Line Shots, Center Point Shots, Crease Shots, High Slot Shots, L Circle Shots, L Corner Shots, L Net Side Shots, L Point Shots, Low Slot Shots, Offensive Neutral Zone Shots, Outside L Shots, Outside R Shots, R Circle Shots, R Corner Shots, R Net Side Shots, R Point Shots, averageTOI, rrWinner, predictions]
Index: []